name: thedivaportraits
favicon: null
layout_spectrum: 0.25135
typography_spectrum: 0.25368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2c5d2'
    - '#010000'
    - '#fffbfc'
    - '#5f6269'
    - '#b2833c'
  brandStrength: 0
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0
purpose: []
